server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payby
    username: root
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"