server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payby?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"