server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    wallet:
      path: /wallet/**
      serviceId: wallet-service
    merchand:
      path: /merchand/**
      serviceId: merchand-service
    admin:
      path: /admin/**
      serviceId: admin-service

ribbon:
  ReadTimeout: 60000